name: Rumble Video Scraper (Selenium)

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu Çek
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          pip install requests selenium webdriver-manager

      - name: Scripti Çalıştır (Selenium ile)
        run: python scrape.py

      - name: Değişiklikleri Gönder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add videos.json
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Selenium: Video listesi güncellendi"
          git push
